nmap <silent> <leader>ga :GoAlternate<CR>
nmap <silent> <leader>gb :GoBuild<CR>
nmap <silent> <leader>gc :GoCallers<CR>
nmap <silent> <leader>gC :GoCallees<CR>
nmap <silent> <leader>gt :GoTest<CR>
nmap <silent> <leader>gf :GoFmt<CR>
nmap <silent> <leader>gy :GoDef<CR>
nmap <silent> <leader>gY :GoDescribe<CR>
nmap <silent> <leader>gd :GoDoc<CR>
